name: Deploy Angular App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 

      - name: Instalar dependências
        run: npm ci
        working-directory: frontend/LinkedOut

      - name: Build do projeto Angular
        run: npm run build -- --configuration=production
        working-directory: frontend/LinkedOut
#
 #     - name: Deploy 
  #      uses: peaceiris/actions-gh-pages@v3
   #     with:
    #      github_token: ${{ secrets.GITHUB_TOKEN }}
      #    publish_dir: frontend/LinkedOut/dist/linked-out
